Added CI rule to run 'make indent'
Signed-off-by: Adrian Reber <adrian@lisas.de>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,3 +24,15 @@ jobs:
         ./autogen.sh
         ./configure ${{ matrix.target }}
         make -j $(nproc)
+    - name: Run make indent
+      if: matrix.target == 'CC=clang CXX=clang++'
+      run: >
+        make indent &&
+        STATUS=$(git status --porcelain) &&
+        if [ ! -z "$STATUS" ]; then
+          echo "FAIL: some files are not correctly formatted.";
+          echo "$STATUS"
+          git diff
+          echo "FAIL: please run 'make indent'";
+          exit 1;
+        fi
